#!/usr/bin/python
import sys,os

'convert %s -trim +repage %s'

if __name__=='__main__':
    print sys.argv
    for f in sys.argv:
        if f[-4:] in ['.eps','.svg','.pdf']:
            print f
            try:
				os.system('convert -density 78x78 "%s" -trim +repage "%s.png"'%(f,f[:-4]))
            except:
                pass




